#!/bin/bash

set -e

root="$(git rev-parse --show-toplevel)"

version=$(git describe --tags --match 'v*' --exact-match) || exit 1

distdir="$root/dist/$version"
builddir="$distdir/build"

cd "$root"

if ! [ -d "$distdir" ]; then
    mkdir -p "$builddir" "$distdir"

    go get -v ./...

    gox -output "$builddir/{{.Dir}}_{{.OS}}_{{.Arch}}/{{.Dir}}" -os 'darwin linux windows' -arch '386 amd64'

    for dir in "$builddir"/*; do
        echo "$dir"
        if [ -d "$dir" ]; then
            cp -R zsh/ "$dir"
            cp ghq.txt "$dir/README.txt"
            ( cd "$dir" && zip -r "$distdir/$(basename "$dir")" ./* )
        fi
    done

    ( cd "$distdir" && shasum $(find * -type f -maxdepth 0) > SHASUMS )
fi

ghr \
    -username motemen \
    -repository ghq \
    -token "$GITHUB_TOKEN" \
    "$version" "$distdir"
