#!/bin/bash

set -e

image=$(docker build -q .)

docker run \
    -v $PWD:/go/src/github.com/motemen/ghq \
    -w /go/src/github.com/motemen/ghq \
    -e GITHUB_TOKEN="$GITHUB_TOKEN" \
    "$image" \
    ./scripts/docker/release
