name: integration
on:
  push:
    branches:
    - master
permissions:
  contents: read
jobs:
  test:
    timeout-minutes: 20
    runs-on: macos-latest
    steps:
    - name: checkout
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      with:
        persist-credentials: false
    - name: setup go
      uses: actions/setup-go@4b73464bb391d4059bd26b0524d20df3927bd417 # v6.3.0
      with:
        go-version-file: go.mod
    - name: install
      run: |
        make install
        brew reinstall git || true
        brew link --overwrite git
        brew install git-svn mercurial fossil breezy darcs
        brew upgrade git-svn mercurial fossil breezy darcs
    - name: test
      run: PATH=$HOME/bin:$PATH ./misc/author/integration_test.sh
