name: release
on:
  push:
    tags:
    - "v[0-9]+.[0-9]+.[0-9]+"
permissions:
  contents: write
  packages: write
jobs:
  release:
    timeout-minutes: 20
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      with:
        persist-credentials: false
    - uses: ./.github/actions/release
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
