name: reviewdog
on: [pull_request]

permissions:
  contents: read
  pull-requests: write
jobs:
  typos:
    permissions:
      contents: read
      pull-requests: write
    timeout-minutes: 10
    name: Spell Check with Typos
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      with:
        persist-credentials: false
    - uses: crate-ci/typos@00f422f3b19c57bc6338715ebfe3316d38768461 # v1.50.3

  staticcheck:
    permissions:
      contents: read
      pull-requests: write
    timeout-minutes: 10
    name: staticcheck
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - name: staticcheck
        uses: reviewdog/action-staticcheck@b2a168b3ea66e3b3d98cc693883d2bc18bc1bffc # v1.32.1
        with:
          reporter: github-pr-review
          level: warning

  misspell:
    permissions:
      contents: read
      pull-requests: write
    timeout-minutes: 10
    name: misspell
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - name: misspell
        uses: reviewdog/action-misspell@7cea3d501cb3834c688e08c89ed77b71764d1784 # v1.30.1
        with:
          reporter: github-pr-review
          level: warning
          locale: "US"

  actionlint:
    permissions:
      contents: read
      pull-requests: write
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - uses: reviewdog/action-actionlint@2085657ab2c7f48c58edcc767fba576f63bea76b # v1.77.0
        with:
          reporter: github-pr-review
