name: tagpr
on:
  push:
    branches:
    - "master"
  workflow_dispatch:
permissions:
  contents: write
  pull-requests: write
  issues: read
jobs:
  tagpr:
    timeout-minutes: 20
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      with:
        persist-credentials: false
    - name: setup go
      uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6.5.0
      with:
        go-version-file: go.mod
    - name: tagpr
      id: tagpr
      uses: Songmu/tagpr@e84001bd5dac8defa0c75b3913937d284a3b3660 # v1.20.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - uses: ./.github/actions/release
      with:
        tag: ${{ steps.tagpr.outputs.tag }}
        token: ${{ secrets.GITHUB_TOKEN }}
      if: "steps.tagpr.outputs.tag != ''"
